"""add lens_grade to sale_records

Revision ID: 4563eaff947c
Revises: 
Create Date: 2026-06-13 15:45:03.781679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4563eaff947c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lens_grade', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale_records', schema=None) as batch_op:
        batch_op.drop_column('lens_grade')

    # ### end Alembic commands ###
